# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f97cf6a392679e957495322e3254b68a1b58ddb1e1bbcdd6049bc3d1996a302e5cf7555ecea6bc6499d12972e488f1f3a840530c12b0322caf16fc5586758e17

test:
  secret_key_base: c3f9ec653a6887271d75273c45acde36c8e1dd411f448d0d534fd24b57fe27ce308bee5a39ce10b589fbc11a2bd7a38da93944f44c42010b279f6b356ea2c3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
